/*
id manual verilə bilər heç bir error çıxmır
*/
CREATE TABLE company
(
    id           SERIAL PRIMARY KEY,
    name         VARCHAR(128) UNIQUE,
    founded_date DATE CHECK ( founded_date > '1995-01-01' AND founded_date < '2020-01-01')
);

/*
Yeni sintaksis SQL standartına yaxın. id manual insert edilmir. manual verildikdə error çıxır.
*/
CREATE TABLE company
(
    id           INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name         VARCHAR(128) UNIQUE,
    founded_date DATE CHECK ( founded_date > '1995-01-01' AND founded_date < '2020-01-01')
);

/*
Yeni sintaksisin alternativi. Burada id manual insert edilə bilər heç bir problem yoxdur.
*/
CREATE TABLE company
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(128) UNIQUE,
    founded_date DATE CHECK ( founded_date > '1995-01-01' AND founded_date < '2020-01-01')
);

DROP TABLE company;

INSERT INTO company (name, founded_date)
VALUES ('Google', '2001-01-01'),
       ('Apple', '2002-10-29'),
       ('Facebook', '1998-09-13');


CREATE TABLE employee
(
    id         INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(128) NOT NULL,
    last_name  VARCHAR(128) NOT NULL,
    salary     INTEGER
);


INSERT INTO employee(first_name, last_name, salary)
VALUES ('Ivan', 'Ivanov', 1000),
       ('Petr', 'Petrov', 2000),
       ('Sveta', 'Svetikova', 1500);

SELECT *
FROM employee;
